language: objective-c
osx_image: xcode8.3
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace SwiftDemo.xcworkspace -scheme SwiftDemo -destination "OS=10.3.1,name=iPhone 7" test | xcpretty
